// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Gender is the predicate function for gender builders.
type Gender func(*sql.Selector)

// Position is the predicate function for position builders.
type Position func(*sql.Selector)

// Title is the predicate function for title builders.
type Title func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
